app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('patient/list', views.patient_list, name='patient_list'),
    path('patient/create', views.patient_create, name='patient_create')
]

first_page/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("", views.index, name="index"),
    path('', include(('app.urls', 'app'), namespace='app'))
]

app/models.py
from django.db import models

# Create your models here.


class Patient(models.Model):
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    age = models.IntegerField()

    

class Intervention(models.Model):
    intervention_date = models.DateField()
    diagnostic = models.CharField(max_length=100)
    procedure_name = models.CharField(max_length=100)


class Procedure(models.Model):
    name = models.CharField()

app/forms.py
from django import forms
from .models import Patient, Intervention, Procedure



class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ["name", "last_name", "email", "age"]

app/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Intervention, Patient, Procedure
from .forms import PatientForm

def index(request):
    return render(request, "app/index.html")

def patient_list(request):
    patient_list = Patient.objects.all()
    return render(request, "app/patient_list.html", context={"patients": patient_list})


def patient_create(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("app:patient_list")
    else:
        form = PatientForm()

    return render(request, "app/patient_create.html", context={"form": form})

app/templates/app/base.html
<!DOCTYPE html> 
<html lang="en"> 
    <head> 
        <meta charset="UTF-8"> 
        <title>Laboratorio | {% block title %} {% endblock title %} </title> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    </head> 
    <body> 
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Laboratorio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/patient/list">Pacientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/procedure/list">Procedimientos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/intervention/list">Intervenciones</a>
                    </li>
                </ul>
                </div>
            </div>
        </nav> 
        <div>
            {% block content_title %} <!-- Titulo de cada página irá aquí --> {% endblock %} 
            {% block content %} <!-- Contenido específico de cada página irá aquí --> {% endblock %} 
        </div> 
    </body> 
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block title %}
    Inicio
{% endblock title %}

{% block content_title %}
    <h1>Laboratorio</h1>
{% endblock content_title %}

{% block content %}
    <div>
        <button>
            <a href="/app/"> Ingresar a Laboratorio </a>
        </button>
    </div>
{% endblock content %}

app/templates/app/patient_create.html
{% extends 'app/base.html' %}

{% block title %} 
    Pacientes
{% endblock title %}


{% block content_title %}
    Creación de Paciente 
{% endblock %} 

{% block content %} 
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Crear">
        <a href="{% url 'app:patient_list' %}"> Cancelar</a>

    </form >

{% endblock %} 
 

app/templates/app/patient_list.html
{% extends 'app/base.html' %}

{% block title %} 
    Pacientes
{% endblock title %}


{% block content_title %}
    <h1>Lista de Pacientes</h1> 
{% endblock %} 

{% block content %} 

    <br><br><a href="{% url 'app:patient_create' %}" class="btn btn-primary m-4">Crear Paciente</a>
    <hr>    
    <ul class="list-group m-4">

        {% for patient in patients %}
            
            <div>
                <h5 class="mb-1"> {{ patient.name }} {{ patient.last_name }}</h5><br>
                <small> Email: {{ patient.email }} </small><br>
                <small> Edad: {{ patient.age }} </small><br>
            </div>
            <hr>

        {% endfor %}
        
    </ul>

{% endblock %} 
 